spring:
  jackson:
    constructor-detector: use_delegating

  jpa:
    open-in-view: false

server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always
